hashicorp/vault-secrets-operator

- demo/infra/app/app.tf
- demo/infra/app/postgres.tf
Update the VDS demo to deploy an app that queries the postgres database using the credentials provided.
> Make the VDS demo more meaningful

- .github/workflows/jira.yaml
Changing "foundations" => "foundations-eco"
> updating jira team to "foundations-eco"

- CHANGELOG.md
Updating changelog to have unreleased line, hoping we'll start adding to it going forward..
> add unreleased line to changelog

- Makefile
- README.md
- test/integration/infra/eks/main.tf
- test/integration/infra/eks/outputs.tf
- test/integration/infra/eks/providers.tf
- test/integration/infra/eks/variables.tf
- test/integration/vaultdynamicsecret_integration_test.go
- test/integration/vaultpkisecret_integration_test.go
- test/integration/vaultstaticsecret_integration_test.go
> Adding testing framework for EKS 

- chart/templates/deployment.yaml
- chart/values.yaml
- test/unit/deployment.bats
Add extra annotation from helm values on deployment.
Closes https://github.com/hashicorp/vault-secrets-operator/issues/168
> feat(helm): add extra annotation on deployment

- chart/templates/leader-election-rbac.yaml
> Add metadata.namespace to Role `leader-election-role` and RoleBinding `leader-election-rolebinding`

- CHANGELOG.md
- api/v1alpha1/vaultdynamicsecret_types.go
- chart/crds/secrets.hashicorp.com_vaultdynamicsecrets.yaml
- config/crd/bases/secrets.hashicorp.com_vaultdynamicsecrets.yaml
- controllers/vaultdynamicsecret_controller.go
Instead of also revoking a previous lease after renewal
As discussed in https://github.com/hashicorp/vault-secrets-operator/pull/170/files#r1184851528
> VDS: only revoke on delete

- CHANGELOG.md
We missed a few changelog updates, adding them.
> update the changelog with unreleased items

- api/v1alpha1/vaultconnection_types.go
- chart/crds/secrets.hashicorp.com_vaultconnections.yaml
- chart/values.yaml
- config/crd/bases/secrets.hashicorp.com_vaultconnections.yaml
Just making it more clear that it's the name of a secret.
> docs: updating doc string for VaultConnection.Spec.CACertSecretRef

- CHANGELOG.md
Change log update for v0.1.0-rc.1 🥳
> Update changelog for v0.1.0-rc.1

- config/default-openshift/kustomization.yaml
- config/default-openshift/manager_resource_patch.yaml
- config/default-openshift/manager_ubi_auth_proxy_patch.yaml
- config/manifests/bases/vault-secrets-operator.clusterserviceversion.yaml
- hack/set_containerImage.sh
- hack/set_openshift_minimum_version.sh
> fixing copyright from the last PR

- controllers/hcpvaultsecretsapp_controller.go
HVSA secrets were no longer be synced after merging #314. The logic used to determine whether or not to do the sync was invalid. We will be adding full acceptance tests soon.
> HVSA: ensure secrets are properly synced

- CHANGELOG.md
- chart/Chart.yaml
- chart/values.yaml
- config/manager/kustomization.yaml
VSO 0.3.0 pre-release that brings in support for synchronizing HCP Vault Secrets Apps.
> Pre-release: v0.3.0-rc.1

- test/integration/hcpvaultsecretsapp/terraform/main.tf
- test/integration/hcpvaultsecretsapp/terraform/variables.tf
- test/integration/hcpvaultsecretsapp_integration_test.go
Ensure that the HCPVS Helm integration tests run correctly during the release.
> Fix HCPVS Helm integration tests

- chart/crds/secrets.hashicorp.com_hcpauths.yaml
- config/crd/bases/secrets.hashicorp.com_hcpauths.yaml
Missed a `make manifest` do to this being a docs PR. Will update the GH workflow in another PR to catch this next time.
> Update CRD manifests

- controllers/hcpvaultsecretsapp_controller.go
- go.mod
These are being added to identify VSO as an HCP client.
> HVSA: include User-Agent and requester HTTP request headers.

- CHANGELOG.md
- chart/Chart.yaml
- chart/values.yaml
- config/manager/kustomization.yaml
Critical bug fix release for #400
> Release v0.3.2

- .github/workflows/build.yaml
- Makefile
- drops k8s-1.23
- adds k8s-1.28
> Test against currently supported k8s versions

- test/integration/hcpvaultsecretsapp_integration_test.go
- Ensure that the generated HVS app name is universally unique
- Add more/better context to test failures in `deleteHVSApp()`
- Only delete the test app when  `ListAppSecrets()` succeeds
> Fix up HCPVS integration tests

- CHANGELOG.md
- chart/Chart.yaml
- chart/values.yaml
- config/manager/kustomization.yaml
Update the changelog and versions for tomorrow's release.
> Release v0.4.0

- scripts/check-versions.sh
> fix minor typo #530

- internal/helpers/rollout_restart.go
Noticed this error was worded a bit oddly for the context
> Update paused deployment error message

- .copywrite.hcl
- LICENSE
Updates year for LICENSE file and copywrite bot config.
> [DO NOT MERGE UNTIL EOY] EOY license update

- api/v1beta1/vaultauth_types.go
- chart/values.yaml
- docs/api/api-reference.md
Mention the environment variables along with their analogous options in the chart. Also update the StorageEncryption doc string.
> Mention environment variable options in chart values

- demo/infra/app/main.tf
- test/integration/hcpvaultsecretsapp/terraform/main.tf
- test/integration/infra/aks/providers.tf
- test/integration/infra/eks/providers.tf
- test/integration/infra/gke/providers.tf
- test/integration/infra/main.tf
- test/integration/operator/terraform/main.tf
- test/integration/revocation/terraform/main.tf
- test/integration/vaultauthmethods/terraform-gcp/main.tf
- test/integration/vaultauthmethods/terraform/main.tf
- test/integration/vaultdynamicsecret/terraform/main.tf
- test/integration/vaultpkisecret/terraform/main.tf
- test/integration/vaultstaticsecret/terraform/main.tf
Update all TF providers to their latest versions.
> Bump TF provider versions

- test/integration/vaultdynamicsecret_integration_test.go
Fix to address https://github.com/hashicorp/vault-secrets-operator/actions/runs/9084815633/job/24966803483#step:3:1734
> Tests: retry VaultConnection updates

- test/integration/vaultdynamicsecret_integration_test.go
Fix to address https://github.com/hashicorp/vault-secrets-operator/actions/runs/9117059775/job/25067232340?pr=753#step:3:1533
> Tests: retry VaultAuth updates

- CHANGELOG.md
> Update changelog for v0.7.1

- chart/Chart.yaml
- chart/values.yaml
- config/manager/kustomization.yaml
Bump versions from 0.7.0 to 0.7.1 for the v0.7.1 release.
> Bump versions

- .github/workflows/build.yaml
- Makefile
> CI: test against k8s 1.30

- .github/workflows/build.yaml
Ensure that we include the LICENSE in the released zip bundle.
> CI: include license in released zip bundle

- chart/templates/deployment.yaml
- chart/templates/hook-upgrade-crds.yaml
- test/unit/deployment.bats
- test/unit/hook-upgrade-crds.bats
Update all Helm hook Jobs to Honor the the manager's `imagePullPolicy` and `imagePullSecrets`.
> Helm(hooks): honor imagePullPolicy and imagePullSecrets

- Makefile
- chart/crds/secrets.hashicorp.com_hcpauths.yaml
- chart/crds/secrets.hashicorp.com_hcpvaultsecretsapps.yaml
- chart/crds/secrets.hashicorp.com_secrettransformations.yaml
- chart/crds/secrets.hashicorp.com_vaultauthglobals.yaml
- chart/crds/secrets.hashicorp.com_vaultauths.yaml
- chart/crds/secrets.hashicorp.com_vaultconnections.yaml
- chart/crds/secrets.hashicorp.com_vaultdynamicsecrets.yaml
- chart/crds/secrets.hashicorp.com_vaultpkisecrets.yaml
- chart/crds/secrets.hashicorp.com_vaultstaticsecrets.yaml
- chart/templates/role.yaml
- config/crd/bases/secrets.hashicorp.com_hcpauths.yaml
- config/crd/bases/secrets.hashicorp.com_hcpvaultsecretsapps.yaml
- config/crd/bases/secrets.hashicorp.com_secrettransformations.yaml
- config/crd/bases/secrets.hashicorp.com_vaultauthglobals.yaml
- config/crd/bases/secrets.hashicorp.com_vaultauths.yaml
- config/crd/bases/secrets.hashicorp.com_vaultconnections.yaml
- config/crd/bases/secrets.hashicorp.com_vaultdynamicsecrets.yaml
- config/crd/bases/secrets.hashicorp.com_vaultpkisecrets.yaml
- config/crd/bases/secrets.hashicorp.com_vaultstaticsecrets.yaml
- config/rbac/role.yaml
- test/chart/chart_test.go
> Build: upgrade controller-gen to 0.16.3

- .github/actions/integration-test/action.yml
- .github/workflows/build.yaml
- Makefile
remove version 1.26.15 and add 1.31.2
> bump k8s version

- .github/actions/integration-test/action.yml
- .github/workflows/build.yaml
- Makefile
- test/integration/infra/scale-testing/deployments/variables.tf
- test/integration/infra/variables.tf
- test/integration/modules/vault/variables.tf
k8s 1.32-1.28, vault 1.19-1.17 plus 1.16(lts)
> ci: update k8s and vault versions

- chart/values.yaml
VSO_GLOBAL_VAULT_OPTION_OPTIONS -> VSO_GLOBAL_VAULT_AUTH_OPTIONS
Seems to correspond to https://github.com/hashicorp/vault-secrets-operator/blob/a3dd6b33ecb0cf9d9af89b6bba8d0df062c6e063/internal/options/env.go#L47
> helm: update values comment
