hashicorp/vault-secrets-operator

.github/workflows/build.yaml, .github/workflows/tests.yaml
Also remove the extra go caching steps in favor of setup-go@v3's [built-in caching support](https://github.com/actions/setup-go/tree/v3.5.0#caching-dependency-files-and-build-outputs).
=> Test with k8s 1.26 and latest Vault versions

hack/install_copywrite.sh
It previously failed with this error:
```
$ make test
Fetching https://github.com/hashicorp/copywrite/releases/download/v0.16.3/SHA256SUMS
Fetching https://github.com/hashicorp/copywrite/releases/download/v0.16.3/copywrite_0.16.3_darwin_x86_64.tar.gz
copywrite_0.16.3_darwin_x86_64.tar.gz: OK
mv: rename /var/folders/kv/rdx7k58x5fj0wb03vgdh6zqh0000gp/T/tmp.wU0r4D42/copywrite to bin/copywrite-0.16.3: No such file or directory
make: *** [copywrite] Error 1
```
It seems like the destination "bin" direcory doesn't exist and needs creating.
=> Fix "make test"

Dockerfile
The build arg `LD_FLAGS` gets dynamically computed on each invocation of `docker build`. This implies that `go mod download` always gets run, even if no dependencies have changed.
By moving `LD_FLAGS` just before `go build`, we ensure that the Docker layer caching is used and that Go dependencies does not unnecessarily have to be downloaded every time.
=> fix: docker cache improvement

config/manager/kustomization.yaml, controllers/vaultstaticsecret_controller.go, test/integration/vaultstaticsecret_integration_test.go
The Operator now detects whenever the owned Destination Secret is deleted. Whenever this situation is encountered, the Operator will recreate/repopulate the Secret.
RefreshAfter must be set and Destination.Create must be set to true for the remediation to take place.
Closes #124
=> VSS: ensure an out-of-band Secret deletion is properly remediated

api/v1alpha1/vaultpkisecret_types.go, config/crd/bases/secrets.hashicorp.com_vaultpkisecrets.yaml
The Vault PKI role should have require_cn  to set false if commonName is not provided.
Closes #150
=> VPS: make commonName optional

.github/workflows/build.yaml, Makefile
We currently restrict the scope of our testing matrix to the latest release of Vault OSS (1.13.1) for the majority of our test environments, with the exception of the `ENT tests using Kustomize` which run against the full test matrix of Vault versions and Kubernetes versions.
This PR changes this so that we deploy using Helm instead of Kustomize for our most expansive test and only run the existing `ENT tests using Kustomize` against `1.13.1`.
* Adds a new Makefile target `integration-test-helm-ent` which runs the integration test with Helm and Vault ENT
* Use this test as the basis for our more expansive tests by introducing and running `ENT tests using Helm` instead of `ENT tests using Kustomize` across all versions of Kubernetes and Vault.
=> Add integration-test-helm-ent and make it the default for matrix

Makefile, config/manager/kustomization.yaml, test/integration/integration_test.go
Move the images block up to prevent 'kustomize edit' from stripping the end of file newline which resulted in a perpetual diff.
=> Set the correct version in the Makefile

CHANGELOG.md, chart/templates/deployment.yaml, test/unit/deployment.bats
Previously setting `controller.kubernetesClusterDomain` in `values.yaml` did not do anything as the templating was incorrect. This PR fixes the deployment templating so that it can be set according to the values.yaml definition.
Fixes #181
=> Fix deployment templating so that kubernetesClusterDomain can be set

CHANGELOG.md, Makefile, api/v1alpha1/vaultdynamicsecret_types.go, config/crd/bases/secrets.hashicorp.com_vaultdynamicsecrets.yaml, controllers/vaultdynamicsecret_controller.go, demo.mk, demo/infra/app/app.tf, demo/infra/app/locals.tf, demo/infra/app/outputs.tf, demo/infra/app/postgres.tf, demo/infra/app/variables.tf, test/integration/vaultdynamicsecret_integration_test.go
This PR ensure that VDS can support any Vault secret engine path.
- drops hard coded `creds` path component.
Example of an updated VDS CR:
```yaml
apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultDynamicSecret
metadata:
name: vso-db-demo-create
namespace: demo-ns
spec:
destination:
create: true
name: vso-db-demo-created
mount: demo-db
path: creds/dev-postgres
rolloutRestartTargets:
- kind: Deployment
name: vso-db-demo
```
**Breaking change:**
- Spec.Role is now Spec.Path
Close #108 #107
=> VDS: allow for specifying an arbitrary secrets path

chart/crds/vaultdynamicsecret-crd.yaml
When working on #172 we missed updating the Helm chart to reflect the new CRD schema.
=> VDS: sync CRD config to Helm chart

CHANGELOG.md, api/v1alpha1/vaultstaticsecret_types.go, chart/crds/secrets.hashicorp.com_vaultstaticsecrets.yaml, config/crd/bases/secrets.hashicorp.com_vaultstaticsecrets.yaml, controllers/vaultstaticsecret_controller.go, test/integration/vaultstaticsecret_integration_test.go
Adds support for specifying the [version](https://developer.hashicorp.com/vault/api-docs/secret/kv/kv-v2#version) of a kv-v2 secret, so that when there are different personas managing the secret contents and the consuming application, they can more easily coordinate rollout and rollback.
=> Support setting kv-v2 version for VaultStaticSecret

Makefile, hack/helm-reference-gen/main.go
* Updates the helm-gen tool and Makefile to use a path to the local copy of the helm documentation in the `hashicorp/vault` website repository.
This was used to generate https://github.com/hashicorp/vault/pull/20776.
=> update helm gen to directly modify files in vault repo

test/integration/vaultauthmethods/terraform/main.tf, test/integration/vaultauthmethods_integration_test.go
This is a follow-on change to #208 which introduced it's own serviceaccount to ensure that we could get a valid JWT token for authentication in the auth method tests.
Instead of creating our own serviceaccount we will use `kubernetes_default_service_account` resources which provide a guarantee that the default serviceaccount for a namespace does exist.
=> Use the kubernetes_default_service_account resource for vaultauthmethod test

.github/workflows/build.yaml, .github/workflows/tests.yaml
Added k8s 1.27 and bumped the other k8s versions. Added the latest vault releases.
Also updated github actions to latest trusted versions (setup-go v4 now caches by default).
=> ci: updating k8s and vault and action versions

internal/common/common.go, internal/helpers/secrets.go, internal/helpers/secrets_test.go, test/integration/integration_test.go, test/integration/vaultauthmethods_integration_test.go, test/integration/vaultdynamicsecret_integration_test.go, test/integration/vaultpkisecret_integration_test.go, test/integration/vaultstaticsecret_integration_test.go
Prior to this fix, whenever `Spec.Destination.Name` changed the previous k8s Secret would remain after the sync. This PR ensures that any previously created k8s secrets that are owned by the Syncable Secret object will be deleted, and only the newly synced secret remains.
=> Ensure any previously created k8s Secrets are cleaned up after sync.

Makefile, chart/templates/default-vault-connection.yaml, chart/values.yaml, test/unit/default-vault-connection.bats
Additional fixes:
- add support for filtering bats tests
- simplify some of the header/params examples
=> chart: make defaultVaultConnection.headers a map

chart/templates/_helpers.tpl, chart/values.yaml, test/unit/default-transit-auth-method.bats, test/unit/default-vault-auth-method.bats
Fixes some typos in the auth method templates and values.yaml that occurred when the templating was changed to a function for auth methods.
There are a couple places where `appRole` is typo'd as `approle` and `roleid` instead of `roleId`, and `secretName` instead of `secretRef` either in the template or values.yaml :( 
The correct naming conventions are intended to be : `appRole`, `roleId`, and `secretRef`.
Fixes the issue reported here:
https://github.com/hashicorp/vault-secrets-operator/pull/155#issuecomment-1585101050
This is technically a breaking change from Beta1 to GA.
=> Fix typos in the chart templates and values.yaml

.github/workflows/build.yaml
The current `integrationTest` job of the `build` workflow creates multiple job runs that are based on the combinations of `kind-k8s-version` and `vault-version` values using matrix. Each run consists of some setup steps (Create K8s Kind Cluster,...), integration test steps (OSS tests using Helm, OSS tests using Kustomize, ENT tests using Helm, ENT tests using Kustomize), and some teardown steps (Store kind cluster logs,...).
Given that integration test steps taking [up to 17 minute each, which takes the build workflow over an hour to run](https://github.com/hashicorp/vault-secrets-operator/actions/runs/5343345048/jobs/9686400849), this PR aims to parallelize these integration test steps to shorten the build workflow time. The PR adds to the `integrationTest` job another matrix "dimension" …
=> use matrix for integration tests

.github/workflows/build.yaml
With the introduction of #282 , the exported kind cluster logs were no longer unique. This PR adapts the log export to include test's package manager and Vault flavor e.g: OSS, ENT.
=> Include Vault flavor and tested package manager in kind log export name

internal/vault/cache_key.go, internal/vault/cache_key_test.go
Since the Client cache key is encoded in the K8s Secret name it needs to follow the K8s specification for resource names, i.e. it can only contain lowercase characters.
To reproduce the issue:
- VSO running with persistent client cache enable
- Deploy a VaultAuth with the `appRole` method specified
=> Ensure client cache keys are always lower cased

controllers/vaultstaticsecret_controller.go
While working on HCP issue I noticed that the error returned from Vault was never being set. The error was being assigned in the wrong scope. This PR ensures that the response error is properly scoped for later evaluation.
=> VSS: fix issue where the response error was not being set

CHANGELOG.md, chart/Chart.yaml, chart/values.yaml, config/manager/kustomization.yaml
Followup to #326 changing release version to 0.2.0 (to match [the new license](https://github.com/hashicorp/vault-secrets-operator/blob/36cdf629d7985c5d09871c43f114eccecbeacc20/LICENSE#L7)).
=> bumping release version to 0.2.0

internal/vault/requests.go, internal/vault/requests_test.go, internal/vault/responses.go, internal/vault/responses_test.go, internal/vault/testutils_test.go, internal/vault/vault_test.go
PR updates some straggler files that still contained the MPL license BUSL-1.1.
=> Update license headers

go.mod, go.sum, internal/vault/cache.go, internal/vault/cache_test.go
golang-lru v0/1 is no longer being maintained. The recommended update path is to move to v2 per:
https://github.com/hashicorp/golang-lru/releases/tag/v1.0.2
=> Upgrade to golang-lru/v2 (v2.0.6)

api/v1beta1/hcpauth_types.go, chart/crds/secrets.hashicorp.com_hcpauths.yaml, config/crd/bases/secrets.hashicorp.com_hcpauths.yaml, controllers/hcpvaultsecretsapp_controller.go, demo/infra/app/hcpvs.tf, demo/infra/app/variables.tf, docs/api/api-reference.md, docs/diags/hcp-secrets.puml, internal/credentials/hcp/service_principal.go, internal/credentials/hcp/service_principal_test.go, test/integration/hcpvaultsecretsapp/terraform/main.tf
In the HCP interface the name of the service-principle's client access key is `clientSecret`. This PR provides better alignment with HCP's naming conventions.
=> HCPVS: rename servicePrinciple data key clientKey to clientSecret

api/v1beta1/vaultdynamicsecret_types.go, chart/crds/secrets.hashicorp.com_vaultdynamicsecrets.yaml, config/crd/bases/secrets.hashicorp.com_vaultdynamicsecrets.yaml, controllers/vaultdynamicsecret_controller.go, controllers/vaultdynamicsecret_controller_test.go, docs/api/api-reference.md
Add support for the upcoming 1.15 Vault feature
- https://github.com/hashicorp/vault/pull/22484
Related docs PR for the feature
- https://github.com/hashicorp/vault/pull/22863
We will update integration tests in a separate PR once https://github.com/hashicorp/terraform-provider-vault/pull/2011 is merged. For now we add a unit test to test the changes made in this PR.
=> support for db schedule-based static role rotations

api/v1beta1/hcpvaultsecretsapp_types.go, api/v1beta1/vaultstaticsecret_types.go, chart/crds/secrets.hashicorp.com_hcpvaultsecretsapps.yaml, chart/crds/secrets.hashicorp.com_vaultstaticsecrets.yaml, chart/templates/deployment.yaml, chart/values.yaml, config/crd/bases/secrets.hashicorp.com_hcpvaultsecretsapps.yaml, config/crd/bases/secrets.hashicorp.com_vaultstaticsecrets.yaml, config/hvsa-tests/kustomization.yaml, config/hvsa-tests/manager_args_patch.yaml, controllers/common.go, controllers/common_test.go, controllers/hcpvaultsecretsapp_controller.go, controllers/vaultstaticsecret_controller.go, demo/infra/app/main.tf, main.go, test/integration/hcpvaultsecretsapp/terraform/main.tf, test/integration/hcpvaultsecretsapp_integration_test.go, test/integration/infra/main.tf, test/integration/modules/vso-helm/main.tf, test/integration/modules/vso-helm/variables.tf, test/integration/revocation/terraform/main.tf, test/integration/vaultauthmethods/terraform/main.tf, test/integration/vaultdynamicsecret/terraform/main.tf, test/integration/vaultpkisecret/terraform/main.tf, test/integration/vaultstaticsecret/terraform/main.tf, test/unit/deployment.bats
Ensure that only support duration string values can be set for `spec.refreshAfter`. This change affects VaultStaticSecret and HCPVaultSecretsApp specs.
In addition to the change above, apply a minimum constraint on the configured HVSA refreshAfter, with the default value being 30s. This value can be set from the command line option `-min-refresh-after-hvsa`.
Additional enhancements:
- chart: support extending the controller.manager's args with the new extraArgs value.
=> Add validation for spec.refreshAfter and min constraints for HVSA

.github/workflows/tests.yaml, Makefile
Add support for running all bats test in parallel. It requires that the `parallel` command be installed on the build host.
=> Support running bats tests in parallel

api/v1beta1/hcpauth_types.go, chart/values.yaml, docs/api/api-reference.md
- helm: hostAliases did not provide a type, which broke Helm documentation generation
- api-ref: the HCPAuthServicePrincipal table contained an extra row.
=> Fix up Helm and API docs for v0.3.0

CHANGELOG.md, chart/Chart.yaml, chart/values.yaml, config/manager/kustomization.yaml
Missed the version bump in the 0.3.0 release, so bumping everything to 0.3.1.
=> Bump the chart version and default tags to 0.3.1

.github/workflows/build.yaml, test/integration/infra/locals.tf, test/integration/infra/main.tf, test/integration/infra/variables.tf
additional changes to the test matrix:
- cycle out vault-1.12
- update vault-1.13.5 to 1.13.8
- update vault-1.14.1 to 1.14.4
other fixes:
- factor out locals from vault/main.tf to locals.tf, making it consistent with the other TF code.
- bump the default vault image tag to 1.15 in vault/variables.tf
=> Add vault-1.15 to the test matrix

.github/workflows/build.yaml, Makefile, scripts/check-versions.sh
Adds a script that verifies that version tags match what the build thinks the `VERSION` should be. This fix  should help to ensure that the Helm/Kustomize/VSO versions are always in sync.
have been updated in both the Helm chart and the Kustomize config.
=> Check Helm and Kustomize versions for production builds.

test/integration/modules/vso-helm/main.tf, test/integration/modules/vso-helm/variables.tf, test/integration/revocation/terraform/main.tf, test/integration/revocation_integration_test.go, test/integration/vaultauthmethods/terraform/main.tf, test/integration/vaultauthmethods_integration_test.go, test/integration/vaultdynamicsecret/terraform/main.tf, test/integration/vaultpkisecret/terraform/main.tf, test/integration/vaultpkisecret/terraform/variables.tf, test/integration/vaultpkisecret_integration_test.go, test/integration/vaultstaticsecret/terraform/main.tf, test/integration/vaultstaticsecret/terraform/variables.tf, test/integration/vaultstaticsecret_integration_test.go
Updates the following integration tests to use the VSO TF Hem module:
- TestVaultAuthMethods
- TestVaultPKISecret
- TestVaultStaticSecret
- TestRevocation (tested locally, since it is disabled)
=> Update remaining integration tests to use the VSO TF Helm module

internal/vault/client.go, internal/vault/client_factory.go, internal/vault/client_test.go
During the VSO restart the Vault Client is restored from the storage cache, but it’s LifetimeWatcher has not yet renewed the client token, which can lead to the next fetch from cache getting an invalid Client (token expired) error. In this situation, the ClientFactory will evict the client from the cache, which in turns calls client.Close(), which has the negative side-effect of setting it’s wrapped api.Client to nil thereby breaking any current Client references that are handling any in-flight requests.
FIxes:
- do not set the wrapped `api.Client` to nil on `Client.Close()`
- attempt to renew the token before starting the `LifetimeWatcher` in `Client.Restore()`
- always wait for the `LiftiemeWatcher` to be started
A work around for this issue is to delete the offending client cache …
=> Handle invalid Client race after restoration

CHANGELOG.md, Makefile, chart/Chart.yaml, chart/values.yaml, config/default/manager_auth_proxy_patch.yaml, config/manager/kustomization.yaml, scripts/check-versions.sh
Includes important security patches applied to Golang and related dependencies.
- critically addresses: CVE-2023-39325
- upgrades kube-rbac-proxy to v0.14.4 addresses the issues mentioned above.
=> Release v0.3.3

Dockerfile
The ubi-micro base image does not include a trusted ca-bundle. This PR adds support for copying the latest bundle from `ubi-minimal:latest` into the target UBI VSO image.
Closes: #412
=> Include the tls-ca-bundle.pem from ubi-minimal

internal/vault/configmap.go, main.go
In #202 we added a feature that revoked the client cache on VSO termination (deployment deletion). The watcher seems to cause a CPU usage spike after VSO has been running for ~1hr. From an strace of an affected VSO process we see that time in `epoll_wait` and `nanosleep` jump 20x from their initial values.
In this PR, we no longer instantiate the ConfigMap watcher.
Partial revert of 8459895c6cf7a7775b8ec14f8dd7a334ef822fa3
Closes #398
=> Remove unneeded instantiation of the VSO ConfigMap watcher

Dockerfile
The invocation of the microdnf command in the UBI build image was blocked waiting for user input when updating the container's RPMs. This PR fixes that, and removes the need to upgrade the the entire container, instead opting to update the ca-certificates package only.
=> UBI: don't block when upgrading ca-certificates

chart/values.yaml, config/default/manager_auth_proxy_patch.yaml
Since we are releasing v0.4.0 imminently, it might be a good time to update to the latest kube-rbac-proxy release: https://github.com/brancz/kube-rbac-proxy/releases/tag/v0.15.0
=> Upgrade kube-rbac-proxy to v0.15.0

Makefile
Make make `check-versions` happy, again.
=> build: bump the kube-rbac-proxy version

.github/workflows/build.yaml
This PR is intended to avoid a [production incident](https://github.com/hashicorp/releng-support/issues/123) where there are duplicate tags (auto-assigned) to UBI images. The entire issue is described [here](https://github.com/hashicorp/crt-workflows-common/pull/407#issue-1999804835), and can be avoided by building `UBI`s (intended for both `Dockerhub` and `Redhat`) in one step.
=> Remove Duplicate UBI Tags

test/integration/vaultauthmethods_integration_test.go
Bumps wait time from 1 minute to 10 minutes.
Aims to get around CI failures where the first GCP auth test fails but the second passes.
=> auth/gke/tests: Increase wait time for eventual consistency

CHANGELOG.md, chart/templates/deployment.yaml, chart/values.yaml, controllers/hcpvaultsecretsapp_controller.go, controllers/vaultpkisecret_controller.go, controllers/vaultstaticsecret_controller.go, main.go, test/unit/deployment.bats
Renames the controller manager flag `--max-concurrent-reconciles-vds` to `--max-concurrent-reconciles` and applies it to VPS, VSS, VHCPSA and VDS controllers.
This has the effect of enabling the all Syncable Secret controllers to process in parallel which we've tested at scale successfully and was causing scaling issues in the current architecture.
The original flag `--max-concurrent-reconciles-vds` is preserved for backward compatibility and will override the new flag for the VDS controller only.
The helm `values.yaml` is updated to reflect the new behaviour of `controller.manager.maxConcurrentReconciles`.
=> rename max-concurrent-reconciles-vds to max-concurrent-reconciles

controllers/common.go, controllers/suite_test.go, controllers/vaultdynamicsecret_controller.go, controllers/vaultdynamicsecret_controller_test.go, test/integration/hcpvaultsecretsapp/terraform/main.tf, test/integration/modules/vso-helm/variables.tf, test/integration/vaultdynamicsecret_integration_test.go
Previously the jitter was a percentage on the static-creds rotation time horizon. In the case where the rotation period/TTL was large e.g. 24h, this would cause the rotation horizon extend beyond the rotation period. This fix ensures that the added jitter is 5% of the constant time duration of 3s.
Closes #466
=> VDS: fix compute static-creds rotation horizon

CHANGELOG.md, chart/templates/_helpers.tpl, chart/templates/default-transit-auth-method.yaml, chart/templates/default-vault-auth-method.yaml, chart/templates/default-vault-connection.yaml, chart/templates/deployment.yaml, chart/templates/leader-election-rbac.yaml, chart/templates/manager-config.yaml, chart/templates/manager-rbac.yaml, chart/templates/metrics-reader-rbac.yaml, chart/templates/metrics-service.yaml, chart/templates/prometheus-servicemonitor.yaml, chart/templates/proxy-rbac.yaml, chart/templates/tests/test-runner.yaml
prefix all helm helper functions with vso to avoid subchart name collision, also renames the function `operator.vaultAuthMethod` to `vso.vaultAuthMethod`.
There seems to be some precedent in other charts, for example the [wordpress chart](https://github.com/bitnami/charts/tree/main/bitnami/wordpress) has a mariadb sub chart, and all of the helpers are prefixed e.g: [https://github.com/bitnami/charts/blob/4caf014953a4f310368b68bcfb4edc576081ea9f/bitnami/wordpress/templates/_helpers.tpl#L12C9-L12](https://github.com/bitnami/charts/blob/4caf014953a4f310368b68bcfb4edc576081ea9f/bitnami/wordpress/templates/_helpers.tpl#L12C9-L12C9)
Fixes #484
Fixes #395
=> prefix all helm helper functions with vso to avoid subchart name collision

api/v1beta1/vaultstaticsecret_types.go, chart/crds/secrets.hashicorp.com_vaultstaticsecrets.yaml, config/crd/bases/secrets.hashicorp.com_vaultstaticsecrets.yaml, controllers/vaultstaticsecret_controller.go
Previously, whenever HMACSecretData was set to true and no data drift was detected, the reconciler would skip destination updates, like annotations, labels etc. This change adds tracking of a resource's generation to determine when the reconciler is handling a resource update.
=> VSS: Ensure all resource updates are synced.

.github/workflows/build.yaml, Dockerfile
Adds a separate ubi image build target and job for the RedHat container registry, that only builds amd64, until we get around our multi-arch issues there.
=> image/ubi: add separate target and build job for RedHat

internal/metrics/metrics.go, internal/vault/cache_storage.go, internal/vault/cache_storage_metrics_test.go, internal/vault/cache_storage_test.go, internal/vault/client_factory.go
Previously, it was possible for invalid client cache storage objects to live forever. This could cause the ClientFactory to fail for valid Client requests. This was most noticeable on a call to RestoreAll() when VSO was first coming up.
Whenever an invalid cached client is found in storage it should be discarded and replaced with a valid client instance.
Other fixes:
- Add more granular metrics for tracking storage deletions which are performed during storage pruning.
- Increase test coverage for cache_storage
- Remove unused EncryptionRequiredError
Closes #364
=> CCS: ensure invalid storage objects are deleted

chart/templates/hcpauth_editor_role.yaml, chart/templates/hcpauth_viewer_role.yaml, chart/templates/hcpvaultsecretsapp_editor_role.yaml, chart/templates/hcpvaultsecretsapp_viewer_role.yaml, chart/templates/vaultauth_editor_role.yaml, chart/templates/vaultauth_viewer_role.yaml, chart/templates/vaultconnection_editor_role.yaml, chart/templates/vaultconnection_viewer_role.yaml, chart/templates/vaultdynamicsecret_editor_role.yaml, chart/templates/vaultdynamicsecret_viewer_role.yaml, chart/templates/vaultpkisecret_editor_role.yaml, chart/templates/vaultpkisecret_viewer_role.yaml, chart/templates/vaultstaticsecret_editor_role.yaml, chart/templates/vaultstaticsecret_viewer_role.yaml, scripts/sync-rbac.sh
There was no need to truncate the ClusterRole names to 63 chars. That limitation is only for label keys. Resource names can be up to 253 chars in length.
=> Drop the editor/viewer ClusterRole name truncation

api/v1beta1/vaultconnection_types.go, chart/crds/secrets.hashicorp.com_vaultconnections.yaml, config/crd/bases/secrets.hashicorp.com_vaultconnections.yaml
Some K8s distros like Rancher do their own Helm chart diff to the running state of a given K8s cluster. For the default VaultConnection provided by Helm chart, the value for spec.skipTLSVerify would always trigger a diff in the case where the corresponding chart value was false, since runtime configuration did not include spec.skipTLSVerify.
Interestingly enough, if the default VaultConnection.spec.skipTLSVerify was added/set to false using 'kubectl edit', the value would persist in the cluster.
Solution:
Update VaultConnectionSpec.SkipTLSVerify to use a default value for rather than setting its JSON flag to omitempty. This will ensure that comparisons between the Helm chart's default VaultConnection's spec.skipTLSVerify can be reliably made, even when the default VC is updated outside of …
=> VC: provide default value for spec.skipTLSVerify

controllers/vaultdynamicsecret_controller.go, test/integration/hcpvaultsecretsapp_integration_test.go, test/integration/integration_test.go, test/integration/vaultdynamicsecret/terraform/outputs.tf, test/integration/vaultdynamicsecret_integration_test.go, test/integration/vaultpkisecret_integration_test.go, test/integration/vaultstaticsecret_integration_test.go
Previously, the VDS controller did not detect when the destination secret had been deleted after it had initially created it.
Fixes:
- ensure a deleted destination secret that is owned by the VDS controller results in a re-sync.
- add integration test to test this use-case
- update all other controller integration tests to test for destination deletion
Closes #228
=> VDS: remediate deleted destination secret

api/v1beta1/hcpvaultsecretsapp_types.go, api/v1beta1/vaultauth_types.go, api/v1beta1/vaultdynamicsecret_types.go, api/v1beta1/vaultpkisecret_types.go, api/v1beta1/vaultstaticsecret_types.go, chart/crds/secrets.hashicorp.com_hcpvaultsecretsapps.yaml, chart/crds/secrets.hashicorp.com_vaultauths.yaml, chart/crds/secrets.hashicorp.com_vaultdynamicsecrets.yaml, chart/crds/secrets.hashicorp.com_vaultpkisecrets.yaml, chart/crds/secrets.hashicorp.com_vaultstaticsecrets.yaml, config/crd/bases/secrets.hashicorp.com_hcpvaultsecretsapps.yaml, config/crd/bases/secrets.hashicorp.com_vaultauths.yaml, config/crd/bases/secrets.hashicorp.com_vaultdynamicsecrets.yaml, config/crd/bases/secrets.hashicorp.com_vaultpkisecrets.yaml, config/crd/bases/secrets.hashicorp.com_vaultstaticsecrets.yaml, docs/api/api-reference.md
Adds namespace requirements for vault auth components to clarify where the serviceaccount/secretRefs need to reside.
=> update api docs to include namespace requirements for auth components

test/integration/hcpvaultsecretsapp_integration_test.go
Pass a fairly large value for maxTries to
assertRemediationOnDestinationDeletion() to help mitigate the effects of the HVS' request rate limiter. Typically, the rate limiter is only ever triggered when there are four or more GH workflows running concurrently.
=> ci: bump max tries for HCPVSA tests

demo.mk, demo/README.md, demo/infra/app/app.tf, demo/infra/app/auth.tf, demo/infra/app/cross-vault-ns.tf, demo/infra/app/hcpvs.tf, demo/infra/app/locals.tf, demo/infra/app/main.tf, demo/infra/app/outputs.tf
Updates the demo to include an example of deploying VSO resources with cross Vault namespace authentication support. Secrets are synced from a secrets engine mounted in a separate Vault namespace.
Setup the demo with the following command:
```
make -f demo.mk VAULT_ENTERPRISE=true docker-build demo
```
=> demo: add cross Vault namespace example

api/v1beta1/common.go, chart/crds/secrets.hashicorp.com_hcpvaultsecretsapps.yaml, chart/crds/secrets.hashicorp.com_vaultdynamicsecrets.yaml, chart/crds/secrets.hashicorp.com_vaultpkisecrets.yaml, chart/crds/secrets.hashicorp.com_vaultstaticsecrets.yaml, config/crd/bases/secrets.hashicorp.com_hcpvaultsecretsapps.yaml, config/crd/bases/secrets.hashicorp.com_vaultdynamicsecrets.yaml, config/crd/bases/secrets.hashicorp.com_vaultpkisecrets.yaml, config/crd/bases/secrets.hashicorp.com_vaultstaticsecrets.yaml, docs/api/api-reference.md, internal/helpers/secrets.go, internal/helpers/secrets_test.go
Adds a new configuration option `spec.destination.overwrite` that when set to true VSO will replace an existing destination secret that it does not currently own. VSO will then take ownership of the destination secret's life-cycle.
Closes #337
=> Take ownership of an existing destination secret

.github/workflows/build.yaml, .github/workflows/tests.yaml
updates:
- actions/checkout -> https://github.com/actions/checkout/releases/tag/v4.1.1
- actions/setup-go -> https://github.com/actions/setup-go/releases/tag/v5.0.0
- actions/setup-node -> https://github.com/actions/setup-node/releases/tag/v4.0.2
incompatible:
- actions/download-artifact -> https://github.com/actions/download-artifact/releases/tag/v4.1.2
- actions/upload-artifact -> https://github.com/actions/upload-artifact/releases/tag/v4.3.1
=> Bump some GH action versions

internal/helpers/template.go, internal/helpers/template_test.go
Ensure that a transformationRef's template overrides are honored.
=> Fix: include global templates only on empty templateRefs

api/v1beta1/common.go, chart/crds/secrets.hashicorp.com_hcpvaultsecretsapps.yaml, chart/crds/secrets.hashicorp.com_vaultdynamicsecrets.yaml, chart/crds/secrets.hashicorp.com_vaultpkisecrets.yaml, chart/crds/secrets.hashicorp.com_vaultstaticsecrets.yaml, config/crd/bases/secrets.hashicorp.com_hcpvaultsecretsapps.yaml, config/crd/bases/secrets.hashicorp.com_vaultdynamicsecrets.yaml, config/crd/bases/secrets.hashicorp.com_vaultpkisecrets.yaml, config/crd/bases/secrets.hashicorp.com_vaultstaticsecrets.yaml, docs/api/api-reference.md
Removes obsolete `spec.destination.transformation.resync` field.
=> API: resync is no longer needed.

api/v1beta1/common.go, chart/crds/secrets.hashicorp.com_hcpvaultsecretsapps.yaml, chart/crds/secrets.hashicorp.com_vaultdynamicsecrets.yaml, chart/crds/secrets.hashicorp.com_vaultpkisecrets.yaml, chart/crds/secrets.hashicorp.com_vaultstaticsecrets.yaml, config/crd/bases/secrets.hashicorp.com_hcpvaultsecretsapps.yaml, config/crd/bases/secrets.hashicorp.com_vaultdynamicsecrets.yaml, config/crd/bases/secrets.hashicorp.com_vaultpkisecrets.yaml, config/crd/bases/secrets.hashicorp.com_vaultstaticsecrets.yaml
Previously, excludeRaw was required, and had a default value. That adds a bit more work for the developer when configuring the CR using an IDE with CRD schema support.
=> Make excludeRaw optional

controllers/vaultdynamicsecret_controller.go, controllers/vaultpkisecret_controller.go
Update the VDS and VPS controllers to call `Prune()` instead of `Remove()` on its reference cache.
=> Fix: prune referrers

controllers/vaultpkisecret_controller.go
The VaultPKISecret controller was missing its SecretTransformation watch. This PR corrects that.
=> VPS: add missing ST watch

api/v1beta1/hcpvaultsecretsapp_types.go, chart/crds/secrets.hashicorp.com_hcpvaultsecretsapps.yaml, config/crd/bases/secrets.hashicorp.com_hcpvaultsecretsapps.yaml, controllers/hcpvaultsecretsapp_controller.go, internal/helpers/secrets.go
Previously, the HCPVSA controller would skip the secret sync if the last sync data HMAC matched. This PR makes the controller behave like all of the secret type controllers, and sync on a generational update.
=> HCPVSA: sync on lastGeneration change

controllers/eventhandlers.go, controllers/eventhandlers_test.go, controllers/hcpvaultsecretsapp_controller.go, controllers/predicates.go, controllers/predicates_test.go, controllers/registry.go, controllers/vaultdynamicsecret_controller.go, controllers/vaultpkisecret_controller.go, controllers/vaultstaticsecret_controller.go, internal/helpers/secrets.go, internal/helpers/secrets_test.go
Previously each secret controller could only detect the deletion of a destination K8s Secret that it owned on the next call to `Reconcile()`. This PR adds support for watching K8s secrets that it owns. Upon deletion, the owner resource will be enqueued for reconciliation with a random delay.
=> Reconcile on secret deletion

chart/templates/deployment.yaml, chart/values.yaml, test/unit/deployment.bats
Add support for setting the imagePullPolicy for the `manager` and `kube-rbac-proxy` containers. The default for both is `IfNotPresent`
=> Chart: support setting imagePullPolicy

controllers/eventhandlers.go, controllers/eventhandlers_test.go, controllers/hcpvaultsecretsapp_controller.go, controllers/registry.go, controllers/registry_test.go, controllers/vaultdynamicsecret_controller.go, controllers/vaultpkisecret_controller.go, controllers/vaultstaticsecret_controller.go, main.go
Previously, the cache was keyed by referent object. This made things simpler for referent management, but it came at the cost of extra memory usage and some added code complexity.
In order to mitigate the potential for encountering an out of memory situation, the cache will map a referring object to its set of references.
Other fixes:
- The previous implementation only supported adding or pruning referrers, which would lead to orphaned references persisting in the cache. So, Add() is replaced by Set(), which sets the set of references for each referring object.
- Make ReferenceCache a private member on all secret controllers.
=> Rework the reference cache

.github/workflows/build.yaml, .github/workflows/tests.yaml, Makefile, hack/.functions
Makes fetching build tools from GH a bit more robust by retrying on transient errors. 
Add support for setting curl's `--retry` option which will retry on any of the following HTTP response codes: 408, 429, 500, 502, 503, 504
Example of a related build failure:
https://github.com/hashicorp/vault-secrets-operator/actions/runs/7922121731/job/21629102539#step:6:19
=> Build: retry GH fetch on transient errors

controllers/common.go, controllers/common_test.go, controllers/hcpvaultsecretsapp_controller.go, controllers/vaultauth_controller.go, controllers/vaultconnection_controller.go, controllers/vaultdynamicsecret_controller.go, controllers/vaultpkisecret_controller.go, controllers/vaultstaticsecret_controller.go
Make updating a resource's status more consistent for all secret controllers, by factoring out the Status.Update() calls to controller methods, and always setting the lastGeneraton from the reconciled object.
The root cause of #608 seems to be API schema differences when going directly from v0.2.0 to v0.5.0. In v0.5.0 we added finalizers the VPS, VSS, and HCPVSA controllers. Finalizers were being added before the object's status was updated, unfortunately that would result in a error that would prevent the secret from ever being  synced, and the object's status from ever being updated. The workaround is documented here: https://github.com/hashicorp/vault-secrets-operator/issues/608#issuecomment-1953010710
The solution is to add the finalizer after the status update. All controllers that …
=> Always add finalizers after status updates

CHANGELOG.md, chart/Chart.yaml, chart/values.yaml, config/manager/kustomization.yaml
Bug fix release for [v0.5.1](https://github.com/hashicorp/vault-secrets-operator/milestone/20). Addresses some issues encountered when upgrading from older versions of VSO.
=> Release v0.5.1

api/v1beta1/vaultdynamicsecret_types.go, chart/crds/secrets.hashicorp.com_vaultdynamicsecrets.yaml, config/crd/bases/secrets.hashicorp.com_vaultdynamicsecrets.yaml
The `rotationSchedule` should be an optional status field, since it is not guaranteed to be provided from the corresponding Vault request.
=> VDS: make rotationSchedule status field optional

chart/values.yaml
Also remove the docstring type for
`controller.manager.globalTransformationOptions` since it's not actually used in the chart as an array.
=> chart values: mention global transformation option env variable

config/manifests/bases/vault-secrets-operator.clusterserviceversion.yaml
Adds the newly required 'features.operators.openshift.io' annotations to the ClusterServiceVersion we submit to OperatorHub.
- [annotation definitions](https://docs.openshift.com/container-platform/4.14/operators/operator_sdk/osdk-generating-csvs.html#osdk-csv-annotations-infra_osdk-generating-csvs)
- [knowledge base article](https://access.redhat.com/articles/7056408)
=> Add new required ClusterServiceVersion annotations

.github/workflows/jira.yaml
The foundations-eco team label may be dropped later.
=> Add vault-eco team label

go.mod, go.sum
Fixes [security scan failure](https://github.com/hashicorp/crt-workflows-common/actions/runs/8173840676) due to https://pkg.go.dev/vuln/GO-2024-2611
=> Bump google.golang.org/protobuf from 1.32.0 to 1.33.0

CHANGELOG.md
Just to warn folks that there may be an issue when upgrading to v0.5.0 via OperatorHub on OpenShift, with a link to [the issue discussing a workaround](https://github.com/hashicorp/vault-secrets-operator/issues/631).
=> Update the changelog with a known issue in v0.5.0

api/v1beta1/vaultdynamicsecret_types.go, chart/crds/secrets.hashicorp.com_vaultdynamicsecrets.yaml, config/crd/bases/secrets.hashicorp.com_vaultdynamicsecrets.yaml, controllers/vaultdynamicsecret_controller.go, controllers/vaultdynamicsecret_controller_test.go, docs/api/api-reference.md
There are some secrets engines that do not provide a lease TTL that the VDS reconciler can use to compute a VDS instances enqueue horizon. This change adds the ability to set a sync duration explicity via the new configuration option: spec.refreshAfter. In the case where the lease TTL is known, spec.refreshAfter will be ignored if set.
=> VDS: support configuring an explicit sync delay

CHANGELOG.md, chart/Chart.yaml, chart/values.yaml, config/manager/kustomization.yaml
Release updates for [v0.5.2](https://github.com/hashicorp/vault-secrets-operator/milestone/21)
=> Release updates for v0.5.2

Makefile, gcp.mk, go.mod, go.sum, test/integration/infra/gke/main.tf, test/integration/infra/gke/providers.tf, test/integration/infra/variables.tf, test/integration/vaultauthmethods/terraform-gcp/main.tf
Update the google terraform provider and module to the latest versions so they match between the infra setup and auth method tests. Set gke `deletion_protection=false` so the cluster can be deleted in CI ([new for v5](https://github.com/hashicorp/terraform-provider-google/blob/main/CHANGELOG.md#500-oct-2-2023)). Bump google.golang.org/api from 0.171.0 to 0.172.0. Bump vault-helm default to 0.27.0.
=> CI: Fix tests in GKE

config/manifests/bases/vault-secrets-operator.clusterserviceversion.yaml
Since they were only needed for v0.5.2
=> olm: remove the `skips` from the last release

test/integration/infra/metrics-server.tf, test/integration/infra/variables.tf
It is nice to have k8s cluster metrics during integration testing.
=> Test infra: install metrics-server

internal/vault/client.go, internal/vault/client_test.go
Previously calling Validate() on a defaultClient that was authenticated using a non-renewable Vault token, would result in an error when the Client was being fetched from the CachingClientFactory. The defaultClient does not start a LifetimeWatcher in this case, so any related validation checks are invalid. This PR corrects that.
=> Client: skip LifetimeWatcher validation for non-renewable auth tokens

internal/vault/client_factory.go, internal/vault/client_factory_test.go
Previously all calls to Get() were serialized using a single lock. This approach does not scale as the number of Vault client grows. With this change locking is done by ClientCacheKey, thereby reducing the overall contention for Vault clients.
=> CachingClientFactory: lock by client cache key

main.go
Disables the "development" zap log options by default. Now all log lines will be structured e.g:
```
{"level":"info","ts":"2024-05-14T20:53:26Z","logger":"controller-runtime.metrics","msg":"Shutting down metrics server with timeout of 1 minute"}
{"level":"info","ts":"2024-05-14T20:53:26Z","msg":"shutting down server","name":"health probe","addr":"[::]:8081"}
{"level":"info","ts":"2024-05-14T20:53:26Z","msg":"Wait completed, proceeding to shutdown the manager"}
```
To enable the old logging behavior VSO should be started with the environment variable `VSO_LOGGER_DEVELOPMENT_MODE` set to a non-empty value.
=> Disable development logger mode by default

chart/templates/_helpers.tpl, chart/templates/deployment.yaml, chart/values.yaml, controllers/hcpvaultsecretsapp_controller.go, controllers/registry.go, controllers/registry_test.go, controllers/vaultdynamicsecret_controller.go, controllers/vaultpkisecret_controller.go, controllers/vaultstaticsecret_controller.go, internal/consts/reasons.go, internal/options/env.go, internal/options/env_test.go, main.go, test/unit/deployment.bats
Previously, the back off duration was based on a fixed duration + some jitter. This PR introduces exponential back offs for all secret syncing controllers. The back off will be calculated and honored whenever an error is encountered while fetching from a secret source e.g: Vault, HCPVS. The back off configuration is controlled via some new command line arguments:
```
-back-off-initial-interval duration
Initial interval between retries on secret source errors. All errors are tried using an exponential backoff strategy. Also set from environment variable VSO_BACK_OFF_INITIAL_INTERVAL. (default 5s)
-back-off-max-interval duration
Maximum interval between retries on secret source errors. All errors are tried using an exponential backoff strategy. Also set from environment variable …
```
=> Use exponential backoffs on secret source errors.

controllers/registry.go
`BackOffRegistry.Get()` is a getter/setter  so it should always lock for rw.
=> Core: lock on get backoff

.github/actions/integration-test/action.yml
Skip storing kind cluster logs on main
Temporary workaround for CRT build prepare issue ref:  https://github.com/hashicorp/bob/pull/189.
=> Skip storing kind cluster logs on main (temporary workaround)

chart/templates/_helpers.tpl, chart/templates/deployment.yaml, chart/values.yaml, test/unit/deployment.bats
See #732 for more details on the originally added feature.
=> Helm: rename backOffOnSecretSourceError to backoffOnSecretSourceError

chart/templates/_helpers.tpl, chart/templates/deployment.yaml, chart/values.yaml, test/unit/deployment.bats
Adds the ability to specify various logging parameters that can be set at VSO controller-manager runtime:
Examples:
```yaml
controller:
manager:
logging:
level: info
timeEncoding: rfc3339
stacktraceLevel: panic
```
=> Helm: adds values for setting VSO's logging options

.github/actions/integration-test/action.yml, .github/workflows/build.yaml
It looks like we were not passing in the VSO version for the build workflow correctly. This PR should fix the versioned builds workflow.
=> Fix versioned build

controllers/vaultdynamicsecret_controller.go, internal/vault/client.go, internal/vault/client_factory.go, internal/vault/client_factory_test.go, internal/vault/client_test.go
Previously, invalidated Clients were removed from the Client cache without calling any of the registered ClientCallbacks. Now any callbacks registered with ClientCallbackOnCacheRemoval be invoked when a client is removed from cache.
This PR extends #717
=> Core: call callbacks on invalidated Client

chart/values.yaml, test/unit/prometheus-servicemonitor.bats
Corrects an issue introduced in #778
Replaces #784 
Ref: https://github.com/hashicorp/vault-secrets-operator/pull/778/files#diff-a9d07052701ab3b718c82ac0fe74b965a8260b06bb5906362081718b0ee593b4R724
=> Helm: fix invalid value name for telemetry.serviceMonitor.enabled

chart/values.yaml, test/unit/prometheus-servicemonitor.bats
Corrects an issue introduced in #778 
Backport of #786
git cherry-pick 21b17f6d911d84dfda76fa8117bf34b05d04fe77
=> Helm: fix invalid value name for telemetry.serviceMonitor.enabled (#786)

.github/actions/integration-test/action.yml
Reverts hashicorp/vault-secrets-operator#766
We can revert #766 since the CRT updates should no longer cause the prepare workflow to fail.
=> Revert "Skip storing kind cluster logs on main (temporary workaround)"

.github/workflows/build.yaml, Dockerfile, Makefile, chart/templates/cluster-role-binding.yaml, chart/templates/clusterrole-aggregated-editor.yaml, chart/templates/clusterrole-aggregated-viewer.yaml, chart/templates/deployment.yaml, chart/templates/hook-upgrade-crds.yaml, chart/templates/tests/test-runner.yaml, chart/values.yaml, go.mod, internal/utils/utils.go, internal/utils/utils_test.go, main.go, test/chart/chart_test.go, test/unit/deployment.bats, test/unit/helpers.bats, test/unit/hook-upgrade-crds.bats
Introduces a pre-upgrade hook that will upgrade/create any of the CRD manifests that are bundled in the vso docker image.
Other fixes:
- make the component label test more reliable by checking all documents individually.
- configure a backoff in the pre-delete "pdcc" Job.
Overview of the approach:
- Extend VSO to support upgrading the CRDs directly
- Include the CRD manifests in the VSO image
- Extend the Helm chart to deploy a pre-upgrade hook that invokes the upgrade process
Out of scope:
- support for rollback/downgrades.
- removal of obsolete CRDs
Update to the Helm values:
```yaml
hooks:
resources:
limits:
cpu: 500m
memory: 128Mi
requests:
cpu: 10m
memory: 64Mi
upgradeCRDs:
enabled: true
backoffLimit:  5
executionTimeout: 30s
```
=> Helm: add support for auto upgrading CRDs

internal/vault/client_factory_test.go
Should resolve issues like: https://github.com/hashicorp/vault-secrets-operator/actions/runs/9370160932/job/25796550858#step:4:1943
=> Give concurrent lockers more time to get the lock

chart/values.yaml, controllers/registry.go, main.go
Other fixes:
- call backoff.Reset() when creating a new BackOff(). That will ensure that the initial interval is honoured
- check that the backoff multiplier is greater than zero
=> Core: update backoff option docs

.github/workflows/build.yaml
Adds a job to denote the success/failure of the build workflow. Once this update is in we can make it a required check under the branch protections for `main`
=> CI: add done job for branch protection status checks

.github/workflows/build.yaml
Since the build-done job determines pass/fail, we can update the build dependency to no longer require unit-tests. That allows us to get the results of the both integration unit tests independently. It also reduces the total workflow execution time by ~2m
Other fixes:
- fail build-done job on workflow cancellation.
=> CI: let unit-tests run in parallel to the build

controllers/vaultdynamicsecret_controller.go, controllers/vaultstaticsecret_controller.go
Updates the VaultStaticSecretReconciler to use a constant backoff when it encounters specific errors during reconciliation. This is the same approach taken in the VDS and VPS controllers.
Previously some reconciliation errors would be passed to the controller's error handling queue, which could lead to very short delays between reconciliation.
=> VSS: use a constant backoff on some reconciliation errors

controllers/hcpauth_controller.go, controllers/secrettransformation_controller.go, controllers/vaultauth_controller.go, controllers/vaultconnection_controller.go, internal/metrics/metrics.go
Previously, VSO would orphan the `controller_resource_status` metric for CRs that have been deleted from the cluster. The fix is to delete the metric for the corresponding controller, namespace, and object name.
=> Core: delete resource status metrics upon object deletion

internal/vault/client_factory.go, internal/vault/client_factory_metrics.go
In hindsight this metric doesn't make sense at this point. It also introduces another high cardinality metric that users probably don't want to have to manage. This metric is better implemented as a collector on the client cache itself, setting the total number of tainted clients would be more meaningful.
=> Drop the tainted client gauge.

chart/templates/clusterrole-aggregated-editor.yaml, chart/templates/clusterrole-aggregated-viewer.yaml, chart/values.yaml, test/unit/clusterrole-aggregates.bats
Extends the `clusterRoleAggregation` configuration to support enabling user-facing ClusterRoles
See https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles for more information.
E.g:
```
controller
rbac:
clusterRoleAggregation:
[...]
userFacingRoles:
view: false
edit: false
```
=> Helm: add support for configuring user-facing roles

.github/actions/integration-test/action.yml, controllers/vaultdynamicsecret_controller.go, controllers/vaultdynamicsecret_controller_test.go, internal/vault/cache.go, internal/vault/cache_key.go, internal/vault/cache_key_test.go, internal/vault/client.go, internal/vault/client_factory.go, internal/vault/client_test.go, test/integration/integration_test.go, test/integration/vaultdynamicsecret/terraform/locals.tf, test/integration/vaultdynamicsecret/terraform/main.tf, test/integration/vaultdynamicsecret/terraform/outputs.tf, test/integration/vaultdynamicsecret/terraform/variables.tf, test/integration/vaultdynamicsecret/terraform/xns.tf, test/integration/vaultdynamicsecret_integration_test.go
In the case where a VaultDynamicSecret instance specifies a Vault namespace that is different from its VaultAuth the ClientCacheKey will be of the clone variant. The cache key format is different from its parent cache key and therefore a parent and a clone cannot be compared. Since the VDS controller stores the clone variant in its state, all instances of this type were ignored during a client callback reconciliation. This would leave unreconciled VDS instances upon client token expiration or other LifetimeWatcher errors.
=> VDS: properly handle the clone cache key variant during client callback execution

controllers/vaultpkisecret_controller.go, controllers/vaultpkisecret_controller_test.go, test/integration/vaultpkisecret/terraform/deployment.tf
This PR automatically includes the issuing CA from Vault in the K8s secret data when the secret's type is `kubernetes.io/tls`. It also modifies the rendering behaviour by omitting any key that does not have a corresponding field in the Vault PKI data.
Sample k8s secret data:
```
apiVersion: v1
data:
ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0[...]
tls.crt: LS0tLS1CRUdJTiB[...]
tls.key: LS0tLS1CRUdJTiB[...]
[...]
kind: Secret
metadata:
creationTimestamp: "2024-07-10T15:01:33Z"
labels:
app.kubernetes.io/component: secret-sync
app.kubernetes.io/managed-by: hashicorp-vso
app.kubernetes.io/name: vault-secrets-operator
secrets.hashicorp.com/vso-ownerRefUID: 6a1d7956-7c5f-4f19-b5fe-2b2cf5114508
name: create-tls-create-0
namespace: vps-6f3gryr35xf21hpf-app
ownerReferences:
- apiVersion: …
```
=> VPS: add ca.crt from issuing CA for tls secret type

chart/templates/_helpers.tpl, chart/templates/default-vault-auth-method.yaml, chart/values.yaml, test/unit/default-vault-auth-method.bats
Add support for configuring the default VaultAuth's `.spec.vaultAuthGlobalRef` from Helm values.
```
helm install ... \
--set 'defaultAuthMethod.enabled=true' \
--set 'defaultAuthMethod.vaultAuthGlobalRef.enabled=true' \
--set 'defaultAuthMethod.vaultAuthGlobalRef.name=foo' \
--set 'defaultAuthMethod.vaultAuthGlobalRef.namespace=baz' \
```
=> Helm: support setting VaultAuthGlobalRef on VaultAuth

controllers/hcpauth_controller.go, controllers/secrettransformation_controller.go, controllers/vaultauth_controller.go, controllers/vaultconnection_controller.go, controllers/vaultpkisecret_controller.go, internal/common/common_test.go, internal/helpers/hmac.go, internal/helpers/serviceaccount.go, internal/helpers/template.go, internal/helpers/template_test.go, internal/vault/cache.go, internal/vault/cache_storage.go, internal/vault/cache_storage_metrics_test.go, test/integration/integration_test.go
The `k8s.io/utils/pointer` package is deprecated, and is being replaced by `k8s.io/utils/ptr`.
=> Migrate to k8s.io/utils/ptr

internal/common/common.go, internal/common/common_test.go
Adds an error wrapper for common VaultAuthGlobal merge errors. This is useful for including error patterns in user facing documentation.
=> Add InvalidMergeError wrapper

.github/workflows/build.yaml
- Test against the latest 1.17.2 version for enterprise and community.
- Test against the latest 1.16.x and 1.15.x for enterprise.
=> CI: Bump test vault versions

internal/vault/client_factory_test.go, main.go
Extends the runtime info log to include the build info of the running VSO instance:
```json
{
"level": "info",
"ts": "2024-07-25T21:41:51Z",
"logger": "setup",
"msg": "Starting manager",
"gitVersion": "v0.7.0-66-gfdf6a90",
"gitCommit": "fdf6a9031e268644bdb9c07fb221fd46fc7474b4",
"gitTreeState": "dirty",
"buildDate": "2024-07-25T21:38:05+0000",
"goVersion": "go1.22.5",
"platform": "linux/amd64",
"clientCachePersistenceModel": "direct-encrypted",
"clientCacheSize": 10000,
"backoffMultiplier": 1.5,
"backoffMaxInterval": 60,
"backoffMaxElapsedTime": 0,
"backoffInitialInterval": 5,
"backoffRandomizationFactor": 0.5,
"globalTransformationOptions": "",
"globalVaultAuthOptions": "allow-default-globals"
}
```
=> Log build info on startup

controllers/common_test.go, controllers/vaultdynamicsecret_controller_test.go, internal/common/common_test.go, internal/credentials/credentials.go, internal/credentials/fake.go, internal/helpers/hmac_test.go, internal/helpers/rollout_restart_test.go, internal/helpers/secrets_test.go, internal/helpers/template_test.go, internal/helpers/testutils_test.go, internal/testutils/ctrlclient.go, internal/vault/client.go, internal/vault/client_factory.go, internal/vault/client_factory_test.go, main.go
Setting up the storage encryption client deadlocks the client factory if the client is deemed to be invalid. This causes all reconciliations to block forever.
The fix is to move the client setup code out of
storageEncryptionClient(). This gets rid of the vestigial recursive call to itself and allows for single locker.
=> Fix: encryption client deadlocking the factory

controllers/hcpvaultsecretsapp_controller.go, internal/helpers/secrets.go, internal/helpers/secrets_test.go
Initial support for rotating secret types in HVS. Fetches them along with static secrets on the same open app secrets API call.
Depends on #889 
Integration tests will be added in a future PR.
=> HVS: rotating secret support

Makefile, chart/values.yaml, config/default/manager_auth_proxy_patch.yaml
Bumping kube-rbac-proxy to 0.18.1 which solves multiple vulnerabilities.
https://github.com/brancz/kube-rbac-proxy/releases/tag/v0.18.1
=> [PSA-2298] bump kube-rbac-proxy to 0.18.1

.github/dependabot.yaml
Follows the work done in vault-csi-provider project: https://github.com/hashicorp/vault-csi-provider/blob/f8fdfd37090297e07a2796b44023bb6c02f12793/.github/dependabot.yaml#L15-L22
Hopefully this will reduce the number of Dependabot PRs and make those PRs more reliable in the case where some dependency update is incomplete.
=> CI: use dependabot groups for Go deps

controllers/hcpvaultsecretsapp_controller.go, controllers/hcpvaultsecretsapp_controller_test.go, test/integration/integration_test.go
Update the HVSA controller to support fetching and listing paginated secret responses.
=> HVSA: add support for response pagination

helpers/secrets.go, helpers/secrets_test.go
Include the values for dynamic and rotating secrets in the destination k8s data. The previous behavior of including prefixed/flattened key values is preserved.
Other fixes:
- guard against nil RotatingVersion and DynamicInstance
- add DynamicInstance tests
- include valid DynamicInstance metadata
=> Include dynamic/rotating values in K8s secret data

.release/security-scan.hcl
Suppress GO-2022-0635 as it is of low severity and VSO isn't using the affected functionalities
Upgrading to latest version of go-secure-stdlib is not possible at this time. The required functionality was inadvertently dropped from github.com/hashicorp/go-secure-stdlib/awsutil during the migration to aws-sdk-go-v2.
Fixes: https://github.com/hashicorp/crt-workflows-common/actions/runs/12589451224/job/35089570078#step:9:1
=> CRT: suppress GO-2022-0635

controllers/hcpvaultsecretsapp_controller.go, controllers/vaultdynamicsecret_controller.go, controllers/vaultpkisecret_controller.go, controllers/vaultstaticsecret_controller.go, helpers/client.go, helpers/secrets.go, main.go
In #982 we disabled caching of all K8s Secrets to address issue where VSO being OOM killed due to the cluster having a large amount of secret data. That change had the side-effect of increasing the number API calls being made to K8s. This PR should reduce the number of calls needed on a cluster running thousands of Vault*Secret instances.
Closes #1000
=> Add new Client for caching VSO owned Secrets

.github/workflows/build.yaml
See https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/approving-workflow-runs-from-public-forks#approving-workflow-runs-on-a-pull-request-from-a-public-fork for more info.
=> Allow running workflows from forked PRs

api/v1beta1/secrettransformation_types.go, chart/crds/secrets.hashicorp.com_secrettransformations.yaml, config/crd/bases/secrets.hashicorp.com_secrettransformations.yaml, docs/api/api-reference.md
This changes the API documentation for SecretTransformation to just use the word "secret" instead of "K8s Secret" in the description of the destination secret, to account for secrets synced by the CSI driver, which does not use K8s Secrets.
Examples of changes to security controls include using new access control methods, adding or removing logging pipelines, etc.
=> Use more generic language for Transformation destination

.github/actions/integration-test/action.yml, .github/workflows/build.yaml, .github/workflows/jira.yaml
Test with k8s 1.33-1.29, latest versions of Vault 1.20-1.18, 1.16.
Also updates the jira-sync team.
Examples of changes to security controls include using new access control methods, adding or removing logging pipelines, etc.
=> ci: Update k8s and vault versions

docs/threat-model/README.md
The new VSO CSI driver functionality shares many of the security concerns of the traditional way of running VSO, but introduces a new threat vector, so I detail it here in a separate section.
Examples of changes to security controls include using new access control methods, adding or removing logging pipelines, etc.
=> Add CSI driver to threat model

test/integration/vaultdynamicsecret_integration_test.go
Fixes flaky `TestVaultDynamicSecret_vaultClientCallback` integration test.
Examples of changes to security controls include using new access control methods, adding or removing logging pipelines, etc.
=> VDS: give the reconciliation check a bit more time.
